# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7097c6a81da1fd1f4c74b2608ef35004d4bc7bd17b9671ca1dbe461cad217658ee8d2533421b8bb525a839d5f5dc86896aaa1cd8b97a84da7a87de5871ca647

test:
  secret_key_base: a6766fd9fa08462b9252c50a39c503a3a34fe26ec7d0084926fd43a45683b3ef861a5b668260c71f7a15fe446eb80738b86c6fdfc58ab72c56282e0bf2f706ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
